---

- name: check if maxscale proxy is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
  register: maxscale

- name: Install MaxScale rpm
  yum:
    name: https://downloads.mariadb.com/MaxScale/2.0.5/rhel/7/x86_64/maxscale-2.0.5-1.rhel.7.x86_64.rpm
    state: present
  when:
    - ansible_distribution_version > '6'
    - inventory_hostname != groups['ndeploydbslave'][0]
    - maxscale.stat.exists == false

- name: Install MaxScale rpm
  yum:
    name: https://downloads.mariadb.com/MaxScale/2.0.5/rhel/6/x86_64/maxscale-2.0.5-1.rhel.6.x86_64.rpm
    state: present
  when:
    - ansible_distribution_version < '7'
    - inventory_hostname != groups['ndeploydbslave'][0]
    - maxscale.stat.exists == false

- synchronize:
    src: /var/lib/maxscale/.secrets
    dest: /var/lib/maxscale/.secrets
  when:
    - maxscale.stat.exists == false
    - inventory_hostname != groups['ndeploydbslave'][0]
    - maxscale.stat.exists == false

- file:
    path: /var/lib/maxscale/.secrets
    owner: maxscale
    group: maxscale
    mode: 0400

- name: Setup MaxScale
  template:
    src: maxscale.cnf.j2
    dest: /etc/maxscale.cnf
  when:
    - inventory_hostname != groups['ndeploydbslave'][0]
    - maxscale.stat.exists == false

- name: Start MaxScale
  service:
    name: maxscale
    state: started
  when:
    - inventory_hostname != groups['ndeploydbslave'][0]

- name: Create mysql.sock
  file:
    src: /tmp/maxscale_mysql.sock
    dest: /var/lib/mysql/mysql.sock
    state: link
  when:  maxscale.stat.exists == false

- name: Create mysql.sock in tmp
  file:
    src: /tmp/maxscale_mysql.sock
    dest: /tmp/mysql.sock
    state: link
  when:  maxscale.stat.exists == false

- file:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
