---

- name: check if Mysql is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
  register: mysqlsetup

- name: check if my.cnf.extra exists
  stat:
    path: /etc/my.cnf.extra
  register: myextrasetup

- name: disable MySQL monitoring
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=mysql enabled=1 monitored=0"
  ignore_errors: yes

- name: Remove MySQL rpm
  yum:
    name: MySQL*
    state: absent
  ignore_errors: yes

- name: Remove MySQL rpm
  yum:
    name: '{{ packages }}'
    state: absent
  vars:
    packages:
      - compat-MySQL51-shared
      - compat-MySQL50-shared
      - mysql-community-common

- name: remove mysql install folder
  file:
    state: absent
    path: /var/lib/mysql/
  when:
    - mysqlsetup.stat.exists == false
    - ansible_distribution_major_version|int == 8


- name: remove .my.cnf file
  file:
    state: absent
    path: /root/.my.cnf
  when:
    - mysqlsetup.stat.exists == false
    - ansible_distribution_major_version|int == 8

- name: Install MariaDB rpm
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - MariaDB-devel
      - MariaDB-common
      - MariaDB-shared
      - MariaDB-server
      - MariaDB-client

- name: Restart MariaDB server
  service: name=mariadb enabled=yes state=started

- name: Copy database dump
  copy:
    src: /root/xtendweb_mysql_all.sql
    dest: /root/xtendweb_mysql_all.sql
  when:  mysqlsetup.stat.exists == false

- name: create the mysql-ssl directory
  file:
    path: /etc/mysql-ssl
    state: directory
  when:
    - mysqlsetup.stat.exists == false

- synchronize:
    src: /etc/mysql-ssl
    dest: /etc/
  when:  mysqlsetup.stat.exists == false

- name: Setup my.cnf.extra
  template:
    src: my.cnf.extra.j2
    dest: /etc/my.cnf.extra
  when:
    - myextrasetup.stat.exists == false

- name: Setup my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  when:
    - mysqlsetup.stat.exists == false

- name: Restart MariaDB server
  service: name=mariadb enabled=yes state=restarted

- name: Update socket path in /root/.my.cnf
  ini_file:
    path: /root/.my.cnf
    section: client
    option: socket
    value: /var/lib/mysql/mysql.sock
    backup: yes
  when:
    - mysqlsetup.stat.exists == false

- name: Import mysqldump from master
  mysql_db:
    state: import
    name: all
    target: /root/xtendweb_mysql_all.sql
  when:  mysqlsetup.stat.exists == false

- name: Copy .my.cnf
  copy:
    src: /root/.my.cnf
    dest: /root/.my.cnf
  when:  mysqlsetup.stat.exists == false

- name: Restart MariaDB server
  service: name=mariadb enabled=yes state=restarted

- name: get the master log and pos
  mysql_replication: mode=getmaster
  register: masterrepl

- set_fact:
    masterlog: "{{ masterrepl.File }}"
    masterpos: "{{ masterrepl.Position }}"

- file:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
