---

- name: check if Mysql is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
  register: mysqlsetup


- name: disable MySQL monitoring
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=mysql enabled=1 monitored=0"
  ignore_errors: yes

- name: Remove MySQL rpm
  yum:
    name: MySQL*
    state: absent

- name: Remove MySQL rpm
  yum:
    name: '{{ item }}'
    state: absent
  with_items:
    - compat-MySQL51-shared
    - compat-MySQL50-shared

- name: Install MariaDB rpm
  yum:
    name: '{{ item }}'
    state: present
  with_items:
    - MariaDB-devel
    - MariaDB-common
    - MariaDB-shared
    - MariaDB-server
    - MariaDB-client

- name: Restart MariaDB server
  service: name=mysql enabled=yes state=started

- name: Copy database dump
  copy:
    src: /root/xtendweb_mysql_all.sql
    dest: /root/xtendweb_mysql_all.sql
  when:  mysqlsetup.stat.exists == false

- name: create the mysql-ssl directory
  file:
    path: /etc/mysql-ssl
    state: directory
  when:
    - mysqlsetup.stat.exists == false

- synchronize:
    src: /etc/mysql-ssl
    dest: /etc/
  when:  mysqlsetup.stat.exists == false

- name: Setup my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  when:
    - mysqlsetup.stat.exists == false

- name: Restart MariaDB server
  service: name=mysql enabled=yes state=restarted

- name: Update socket path in /root/.my.cnf
  ini_file:
    path: /root/.my.cnf
    section: client
    option: socket
    value: /var/lib/mysql/mysql.sock
    backup: yes
  when:
    - mysqlsetup.stat.exists == false

- name: Workaround for MySQL-python compile in MariaDB10.2
  lineinfile:
    path: /usr/include/mysql/mysql.h
    insertbefore: 'struct st_mysql_options options;'
    line: 'unsigned int reconnect;'
  when:
    - mariadb == 10.2

- name: Install MySQL-python
  pip:
    name: MySQL-python
    state: present

- name: Import mysqldump from master
  mysql_db:
    state: import
    name: all
    target: /root/xtendweb_mysql_all.sql
  when:  mysqlsetup.stat.exists == false

- name: Copy .my.cnf
  copy:
    src: /root/.my.cnf
    dest: /root/.my.cnf
  when:  mysqlsetup.stat.exists == false

- name: Restart MariaDB server
  service: name=mysql enabled=yes state=restarted

- name: get the master log and pos
  mysql_replication: mode=getmaster
  register: masterrepl

- set_fact:
    masterlog: "{{ masterrepl.File }}"
    masterpos: "{{ masterrepl.Position }}"

- file:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
