---

- name: check if Mysql is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
  register: mysqlsetup

- name: check if my.cnf.extra exists
  stat:
    path: /etc/my.cnf.extra
  register: myextrasetup

- name: disable MySQL monitoring
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=mysql enabled=1 monitored=0"
  ignore_errors: yes

- name: Remove MySQL rpm
  yum:
    name: MySQL*
    state: absent
  ignore_errors: yes

- name: Remove MySQL rpm
  yum:
    name: '{{ packages }}'
    state: absent
  vars:
    packages:
      - compat-MySQL51-shared
      - compat-MySQL50-shared
      - mysql-community-common

- name: Install MySQL-python
  yum: name={{ packages }} enablerepo={{ repo }},epel state=present
  vars:
    packages:
     - MySQL-python
  when:
    - ansible_distribution_major_version|int == 7

- name: remove mysql install folder
  file:
    state: absent
    path: /var/lib/mysql/
  when:
    - mysqlsetup.stat.exists == false
    - ansible_distribution_major_version|int == 8


- name: remove .my.cnf file
  file:
    state: absent
    path: /root/.my.cnf
  when:
    - mysqlsetup.stat.exists == false
    - ansible_distribution_major_version|int == 8

- name: Install MariaDB rpm
  yum:
    name: "{{ packages }}"
    state: present
  vars:
    packages:
      - MariaDB-devel
      - MariaDB-common
      - MariaDB-shared
      - MariaDB-server
      - MariaDB-client
      - MariaDB-backup

- name: Stop MariaDB server
  service: name=mariadb state=stopped

- name: remove MariaDB install folder
  file:
    state: absent
    path: /var/lib/mysql/
  when:
    - mysqlsetup.stat.exists == false

- name: Create /backup directory if it does not exist
  file:
    path: /backup
    state: directory
    mode: '0755'

- name: Copy mariabackup folder from master
  synchronize:
    src: /backup/autom8n_mysqlbackup
    dest: /backup/
  when:  mysqlsetup.stat.exists == false

- name: mariabackup prepare
  shell: mariabackup --prepare --target-dir=/backup/autom8n_mysqlbackup
  when:
    - mysqlsetup.stat.exists == false

- name: mariabackup copy back
  shell: mariabackup --copy-back --target-dir=/backup/autom8n_mysqlbackup
  when:
    - mysqlsetup.stat.exists == false

- name: set mysql folder ownership
  file:
    path: /var/lib/mysql
    owner: mysql
    group: mysql
    recurse: yes

- name: set mysql folder permission
  file:
    path: /var/lib/mysql
    mode: 0755


#- name: Copy database dump
#  copy:
#    src: /root/xtendweb_mysql_all.sql
#    dest: /root/xtendweb_mysql_all.sql
#  when:  mysqlsetup.stat.exists == false

- name: create the mysql-ssl directory
  file:
    path: /etc/mysql-ssl
    state: directory
  when:
    - mysqlsetup.stat.exists == false

- synchronize:
    src: /etc/mysql-ssl
    dest: /etc/
  when:  mysqlsetup.stat.exists == false

- name: Setup my.cnf.extra
  template:
    src: my.cnf.extra.j2
    dest: /etc/my.cnf.extra
  when:
    - myextrasetup.stat.exists == false

- name: Setup my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  when:
    - mysqlsetup.stat.exists == false

#- name: Update socket path in /root/.my.cnf
#  ini_file:
#    path: /root/.my.cnf
#    section: client
#    option: socket
#    value: /var/lib/mysql/mysql.sock
#    backup: yes
#  when:
#    - mysqlsetup.stat.exists == false

#- name: Import mysqldump from master
#  mysql_db:
#    state: import
#    name: all
#    target: /root/xtendweb_mysql_all.sql
#  when:  mysqlsetup.stat.exists == false

- name: Copy .my.cnf
  copy:
    src: /root/.my.cnf
    dest: /root/.my.cnf
  when:  mysqlsetup.stat.exists == false

- name: Restart MariaDB server
  service: name=mariadb enabled=yes state=restarted


- file:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
