---

- name: Ensure services on slave are started
  service: name={{ item }} enabled=yes state=started
  with_items:
    - nginx

- name: Ensure csync2 on slave is started
  service: name=csync2.socket enabled=yes state=started
  when: ansible_distribution_major_version == "7"

- name: Ensure csync2 on slave is started
  service: name=xinetd enabled=yes state=restarted
  when: ansible_distribution_major_version == "6"

- name: Start redis on slave
  service: name=redis enabled=yes state=started

- name: Stop dovecot on slave
  service: name=dovecot enabled=no state=stopped

- name: Disable tailwatchd drivers
  shell: "{{ item }}"
  with_items:
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::APNSPush"
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::ChkServd"
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::Eximstats"
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::MailHealth"
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::ModSecLog"
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::RecentAuthedMailIpTracker"
    - "/usr/local/cpanel/libexec/tailwatchd --disable=Cpanel::TailWatch::cPBandwd"
  ignore_errors: yes

- name: Ensure cPanel updates are set to manual
  lineinfile:
    path: /etc/cpupdate.conf
    regexp: '^UPDATES='
    line: 'UPDATES=manual'
