---

- name: Ensure services on slave are started
  service: name={{ item }} enabled=yes state=started
  with_items:
    - nginx

- name: Ensure csync2 on slave is started
  service: name=csync2.socket enabled=yes state=started
  when: ansible_distribution_major_version == "7"

- name: Ensure csync2 on slave is started
  service: name=xinetd enabled=yes state=restarted
  when: ansible_distribution_major_version == "6"
