---

- name: Ensure services on slave are started
  service: name={{ item }} enabled=yes state=started
  with_items:
    - nginx

- name: Ensure csync2 on slave is started
  service: name=csync2.socket enabled=yes state=started

- name: Start redis on slave
  service: name=redis enabled=yes state=started

- name: Ensure Dovecot service is running
  service: name=dovecot enabled=yes state=started

- name: disable spamd
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=spamd enabled=0 monitored=0"
  ignore_errors: yes

- name: disable cpanellogd
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=cpanellogd enabled=0 monitored=0"
  ignore_errors: yes

- name: disable cpdavd
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=cpdavd enabled=0 monitored=0"
  ignore_errors: yes

- name: disable cphulkd
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=cphulkd enabled=0 monitored=0"
  ignore_errors: yes

- name: disable cpanellogd
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=cpanellogd enabled=0 monitored=0"
  ignore_errors: yes

- name: Ensure cPanel updates are set to manual
  lineinfile:
    path: /etc/cpupdate.conf
    regexp: '^UPDATES='
    line: 'UPDATES=manual'
