---

- name: Ensure services on slave are started
  service: name={{ item }} enabled=yes state=started
  with_items:
    - nginx

- name: Ensure csync2 on slave is started
  service: name=csync2.socket enabled=yes state=started
  when: ansible_distribution_major_version == "7"

- name: Ensure csync2 on slave is started
  service: name=xinetd enabled=yes state=restarted
  when: ansible_distribution_major_version == "6"

- name: Start redis on slave
  service: name=redis enabled=yes state=started

- name: Stop dovecot on slave
  service: name=dovecot enabled=no state=stopped

- name: restart tailwatchd
  shell: "/usr/local/cpanel/libexec/tailwatchd --stop"
  ignore_errors: yes

- name: kill any tailwatchd process
  shell: "killall -9 tailwatchd"
  ignore_errors: yes

- name: Ensure cPanel updates are set to manual
  lineinfile:
    path: /etc/cpupdate.conf
    regexp: '^UPDATES='
    line: 'UPDATES=manual'
