---

- name: check if maxscale proxy is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
  register: maxscale

- name: create the mysql-ssl directory
  file:
    path: /etc/mysql-ssl
    state: directory
  when:
    - maxscale.stat.exists == false

- synchronize:
    src: /etc/mysql-ssl
    dest: /etc/
  when:  maxscale.stat.exists == false

- name: Install MaxScale rpm
  yum:
    name: https://dlm.mariadb.com/1496729/MaxScale/2.5.7/packages/rhel/7/maxscale-2.5.7-1.rhel.7.x86_64.rpm
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_distribution_major_version|int == 7
    - inventory_hostname != groups['ndeploydbslave'][0]

- name: Install MaxScale rpm
  yum:
    name: https://dlm.mariadb.com/1496724/MaxScale/2.5.7/packages/rhel/8/maxscale-2.5.7-1.rhel.8.x86_64.rpm
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_distribution_major_version|int == 8
    - inventory_hostname != groups['ndeploydbslave'][0]

- synchronize:
    src: /var/lib/maxscale/.secrets
    dest: /var/lib/maxscale/.secrets
  when:
    - maxscale.stat.exists == false
    - inventory_hostname != groups['ndeploydbslave'][0]
    - maxscale.stat.exists == false

- file:
    path: /var/lib/maxscale/.secrets
    owner: maxscale
    group: maxscale
    mode: 0400

- name: Setup Maxscale switchover script
  template:
    src: failover.sh.j2
    dest: /var/lib/maxscale/failover.sh
  when:
    - maxscale.stat.exists == false

- file:
    path: /var/lib/maxscale/failover.sh
    owner: maxscale
    group: maxscale
    mode: 0750

- name: Setup MaxScale
  template:
    src: maxscale.cnf.j2
    dest: /etc/maxscale.cnf
  when:
    - inventory_hostname != groups['ndeploydbslave'][0]
    - maxscale.stat.exists == false

- name: check if CageFS is active
  stat:
    path: /usr/sbin/cagefsctl
  register: cagefs

- name: Cagefsctl remount
  shell: /usr/sbin/cagefsctl --remount-all
  when:
    - cagefs.stat.exists == true

- name: Start MaxScale
  service:
    name: maxscale
    enabled: yes
    state: started

- file:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
