---

- name: check if Mysql is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
  register: mysqlsetup

- name: Disable chkservd monitoring of mysql-ssl
  lineinfile:
    path: /etc/chkserv.d/chkservd.conf
    state: absent
    line: 'mysql:1'

- name: Restart chkservd
  shell: /scripts/restartsrv_chkservd
  ignore_errors: yes

- name: create the mysql-ssl directory
  file:
    path: /etc/mysql-ssl
    state: directory
  when:
    - mysqlsetup.stat.exists == false

- name: Secure mysql
  template:
    src: genssl.j2
    dest: /root/xtendweb_mysql_secure.sh
    mode: 755
  when:
    - mysqlsetup.stat.exists == false

- name: Generate certs
  shell: /root/xtendweb_mysql_secure.sh
  when:
    - mysqlsetup.stat.exists == false

- name: Setup my.cnf
  template:
    src: my.cnf.j2
    dest: /etc/my.cnf
  when:
    - mysqlsetup.stat.exists == false

- name: Update socket path in /root/.my.cnf
  ini_file:
    path: /root/.my.cnf
    section: client
    option: socket
    value: /var/lib/mysql/mysq.sock
    backup: yes
  when:
    - mysqlsetup.stat.exists == false

- name: Restart MariaDB server
  service: name=mysql enabled=yes state=restarted
  when:
    - mysqlsetup.stat.exists == false

- name: Generate mysql grants
  template:
    src: mysqlgrants.j2
    dest: /root/xtendweb_mysql_grants.sql
  when:
    - mysqlsetup.stat.exists == false

- name: Setup mysql grants
  shell: mysql < /root/xtendweb_mysql_grants.sql
  when:
    - mysqlsetup.stat.exists == false

- name: get the master log and pos
  mysql_replication: mode=getmaster
  register: masterrepl

- name: Dump all databases
  mysql_db:
    state: dump
    name: all
    target: /root/xtendweb_mysql_all.sql
    single_transaction: True
  when:
    - mysqlsetup.stat.exists == false

- set_fact:
    masterlog: "{{ masterrepl.File }}"
    masterpos: "{{ masterrepl.Position }}"

- file:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
