---

- name: Setup dns zonetemplates on master
  template:
    src: "{{ item }}"
    dest: /var/cpanel/zonetemplates/{{ item }}
  with_items:
    - root_simple.j2
    - root_standard.j2
    - root_standardvirtualftp.j2
