---

- name: Ensure csync2 on master is started
  service: name=csync2.socket enabled=yes state=started
  when: ansible_distribution_major_version == "7"

- name: Ensure csync2 on master is started
  service: name=xinetd enabled=yes state=restarted
  when: ansible_distribution_major_version == "6"

- name: remove old csync2 cron job
  cron:
    name: nDeploy csync2
    state: absent

- name: Add csync2 cron job in /etc/crontab
  cron:
    name: XtendWeb csync2
    cron_file: "/etc/crontab"
    user: root
    job: "/usr/sbin/csync2 -x"

- name: Restart crond on master
  service: name=crond enabled=yes state=restarted

- name: Create user and homedir across the slaves
  shell: /opt/nDeploy/scripts/cluster_home_ensure_all.py

- name: Start unison on master
  service: name=ndeploy_unison enabled=yes state=restarted
  when:
    - ansible_lsb.major_release|int < 7

- name: Start unison on master
  shell: "systemctl stop ndeploy_unison && systemctl start ndeploy_unison"
  when:
    - ansible_lsb.major_release|int >= 7

- name: enable unison on master
  shell: "systemctl enable ndeploy_unison"
  when:
    - ansible_lsb.major_release|int >= 7

- name: Start redis on master
  service: name=redis enabled=yes state=started

- name: Start ndeploy_geodns on master
  service: name=ndeploy_geodns enabled=yes state=started
