---
- name: Gather facts about the slaves
  hosts: ndeployslaves
  tasks: []

- name: Setup XtendWeb cluster on master cPanel server
  hosts: ndeploymaster
  connection: local
  roles:
    - install_master
    - csync2_master
    - unison_master
    - mysqlaccess_master
    - clusterdirs_master
    - new_dns_master

- name: Setup XtendWeb cluster on slaves
  hosts: ndeployslaves
  roles:
    - install_slave
    - csync2_slave
    - new_dns_slave
    - services_slave
    - domlog_rotate_slave
    - copyrepos_slave
    - mkaccesshash_slave

- name: Setup Stunnel and HAProxy
  hosts: ndeploymaster
  connection: local
  roles:
    - stunnel_master
    - haproxy_master

- name: Setup Stunnel and HAProxy
  hosts: ndeployslaves
  roles:
    - stunnel_slave
    - haproxy_slave

- name: Setup DNS cluster config on slaves
  hosts: ndeployslaves
  vars:
     accesshash: "{{ lookup('file', '/root/xtendweb_accesshash_temp_{{ ansible_nodename }}') }}"
  roles:
    - dnscluster_slave

- name: setup csync2 service on master
  hosts: ndeploymaster
  roles:
    - services_master

- name: MariaDB setup on master
  hosts: ndeploymaster
  vars:
    MYSQLPASS: "{{ lookup('ini', 'password section=client file=/root/.my.cnf') }}"
  roles:
    - new_mariadb_master

- name: MariaDB setup on slave
  hosts: ndeployslaves
  vars:
    MYSQLPASS: "{{ lookup('ini', 'password section=client file=/root/.my.cnf') }}"
  roles:
    - new_mariadb_slave

- name: Start MySQL replication on master
  hosts: ndeploymaster
  vars:
    MYSQLPASS: "{{ lookup('ini', 'password section=client file=/root/.my.cnf') }}"
  roles:
    - dbreplication_master

- name: Start MySQL replication on slave
  hosts: ndeployslaves
  vars:
    MYSQLPASS: "{{ lookup('ini', 'password section=client file=/root/.my.cnf') }}"
  roles:
    - dbreplication_slave

- name: MaxScale setup init on master
  hosts: ndeploymaster
  vars:
    MYSQLPASS: "{{ lookup('ini', 'password section=client file=/root/.my.cnf') }}"
  roles:
    - new_maxscale_initmaster

- name: MaxScale setup on master
  hosts: ndeploymaster
  vars:
    MAXSCALEPASS: "{{ lookup('file', '/root/xtendweb_maxscale') }}"
  roles:
    - new_maxscale_master

- name: MaxScale setup on DB slave
  hosts: ndeploydbslave
  vars:
    MAXSCALEPASS: "{{ lookup('file', '/root/xtendweb_maxscale') }}"
    MYSQLPASS: "{{ lookup('ini', 'password section=client file=/root/.my.cnf') }}"
  roles:
    - new_maxscale_dbslave

- name: MaxScale setup on slave
  hosts: ndeployslaves
  vars:
    MAXSCALEPASS: "{{ lookup('file', '/root/xtendweb_maxscale') }}"
  roles:
    - new_maxscale_slave

- name: Switch to GTID
  hosts: ndeploymaster,ndeployslaves
  roles:
    - gtid_db

- name: BackupMX setup on master
  hosts: ndeploymaster
  roles:
    - backupmx_master

- name: BackupMX setup on master
  hosts: ndeployslaves
  roles:
    - backupmx_slave

- name: Sync cPanel config
  hosts: ndeployslaves
  roles:
    - cpconfig_slave

- name: Setup ipmap do dnssync
  hosts: ndeploymaster
  roles:
    - ipmap_master

- name: Setup PHP-FPM app server on master
  hosts: ndeploymaster
  roles:
    - php_master
    - httpd_master

- name: Setup PHP-FPM app server on slaves
  hosts: ndeployslaves
  roles:
    - php_slave
    - httpd_slave

- name: Setup HHVM extras for master
  hosts: ndeploymaster
  roles:
    - hhvm_master

- name: Setup HHVM extras for slaves
  hosts: ndeployslaves
  roles:
    - hhvm_slave

- name: Remove temp files from master
  hosts: ndeploymaster
  roles:
    - cleanup_master

- name: Remove temp files from slaves
  hosts: ndeployslaves
  roles:
    - cleanup_slave
