---
- name: Gather facts about the slaves
  hosts: ndeployslaves
  tasks: []

- name: Setup nDeploy cluster on master cPanel server
  hosts: ndeploymaster
  connection: local
  roles:
    - install_master
    - csync2_master
    - unison_master
    - lsyncd_master

- name: Setup nDeploy cluster on slaves
  hosts: ndeployslaves
  roles:
    - install_slave
    - csync2_slave
    - lsyncd_slave
    - services_slave
    - backupmx_slave

- name: setup csync2 service on master
  hosts: ndeploymaster
  roles:
    - services_master
