---

- name: disable named service
  shell: "/scripts/setupnameserver --force disabled"

- name: Initialize MaxMind GeoLite database
  shell: /etc/gdnsd/geoip/geoip_update.sh

- name: Remove old server status check cron job
  cron:
    name: nDeploy status check
    state: absent
