---

- name: Create the accesshash on slave server
  shell: /usr/local/cpanel/bin/mkaccesshash
  args:
    creates: /root/.accesshash

- name: Remove line breaks from accesshash
  shell: tr -d '\n' < /root/.accesshash > /root/xtendweb_accesshash_temp

- name: Fetch the accesshash to master
  fetch:
    src: /root/xtendweb_accesshash_temp
    dest: /root/xtendweb_accesshash_temp_{{ inventory_hostname }}
    flat: yes
