---

- name: Generate API token
  shell: /opt/nDeploy/scripts/cluster_access_token_generate.py

- name: check if token generated ok
  stat:
    path: /root/xtendweb_accesshash_temp
  register: accesstoken


- name: Fetch the API token to master
  fetch:
    src: /root/xtendweb_accesshash_temp
    dest: /root/xtendweb_accesshash_temp_{{ inventory_hostname }}
    flat: yes
  when:
    - accesstoken.stat.exists == true
