---
#This playbook will install and setup unison on nDeploy cluster(master)


- name: Install and setup unison in nDeploy cluster master
  file: path=/root/.unison state=directory

- name: create the unison preference file
  template:
    src: default.prf.j2
    dest: /root/.unison/{{ item[0] }}{{ item[1] }}.prf
    # force: no
  with_nested:
    - "{{ homedir }}"
    - "{{ groups['ndeployslaves'] }}"
