---

- name: disable named service
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=named enabled=0 monitored=0"
  ignore_errors: yes

- name: Stop named
  service:
    name: named
    state: stopped

- name: Initialize MaxMind GeoLite database
  shell: /opt/geodns-nDeploy/GeoIP/geoip_update.sh

- name: Allow server status check from all cluster nodes
  template:
    src: nginx_status_allow.conf.j2
    dest: /etc/nginx/conf.d/nginx_status_allow.conf

- name: Create geoDNS cluster data yaml
  template:
    src: geodns_cluster.yaml.j2
    dest: /opt/geodns-nDeploy/dns-data/geodns_cluster.yaml

- name: Add server status check cron job
  cron: name="nDeploy status check" user=root job="/opt/nDeploy/scripts/cluster_server_status_check.py"
