---

- name: disable named service
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=named enabled=0 monitored=0"
  ignore_errors: yes
  when: dns == "geodns"

- name: Stop named
  service:
    name: named
    state: stopped
  when: dns == "geodns"

- name: Initialize MaxMind GeoLite database
  shell: /opt/geodns-nDeploy/GeoIP/geoip_update.sh

- name: Remove old server status check cron job
  cron:
    name: nDeploy status check
    state: absent

- name: Add server status check cron job in /etc/crontab
  cron:
    name: XtendWeb status check
    cron_file: "/etc/crontab"
    user: root
    job: "/opt/nDeploy/scripts/cluster_server_status_check.py"
  when: dns == "geodns"    
