---

- name: get the slave status
  mysql_replication: mode=getreplica
  register: slavestatus
  when:
    - ansible_distribution_major_version|int == 8

- name: get the slave status
  mysql_replication: mode=getslave
  register: slavestatus
  when:
    - ansible_distribution_major_version|int == 7 

- name: Setup gtid replication
  shell: mysql -e "STOP SLAVE;"
  when:
    - slavestatus.Using_Gtid == "No"

- name: Setup gtid replication
  shell: mysql -e "CHANGE MASTER TO MASTER_USE_GTID=slave_pos;"
  when:
    - slavestatus.Using_Gtid == "No"

- name: Setup gtid replication
  shell: mysql -e "START SLAVE;"
  when:
    - slavestatus.Using_Gtid == "No"
