---

- name: Ensure EPEL repo is present
  yum: name={{ item }} state=present
  with_items:
    - epel-release

- name: Install nDeploy repo
  yum: name={{ item }} state=present disable_gpg_check=yes validate_certs=False
  with_items:
    - https://github.com/AnoopAlias/nDeploy/raw/master/nDeploy-release-centos-1.0-3.noarch.rpm

- name: Install nDeploy cluster slave rpm packages
  yum: name={{ item }} enablerepo=ndeploy,epel state=present
  with_items:
   - csync2-nDeploy
   - unison-nDeploy
   - nginx-nDeploy
   - nDeploy-cluster-slave

- name: ensure default UMASK is in place
  lineinfile: dest=/etc/login.defs state=absent regexp="^UMASK"
