---

- name: Ensure EPEL repo is present
  yum: name={{ item }} state=present
  with_items:
    - epel-release
    - redhat-lsb-core

- name: Install XtendWeb repo
  yum: name={{ item }} state=present disable_gpg_check=yes validate_certs=False
  with_items:
    - https://github.com/AnoopAlias/XtendWeb/raw/ndeploy4/nDeploy-release-centos-1.0-7.noarch.rpm

- name: Install XtendWeb cluster rpm packages
  yum: name={{ item }} enablerepo=ndeploy-edge,epel state=present
  with_items:
   - csync2-nDeploy
   - unison-nDeploy
   - "{{ webserver }}-nDeploy"
   - python-pip
   - stunnel
   - redis
   - haproxy
   - geodns-nDeploy

- name: Install XtendWeb cluster slave rpm package
  yum: name={{ item }} enablerepo=ndeploy-edge,epel state=present
  with_items:
   - nDeploy-cluster-slave

- name: ensure default UMASK is in place
  lineinfile: dest=/etc/login.defs state=absent regexp="^UMASK"

- name: create default vhost config in slave
  shell: /opt/nDeploy/scripts/generate_default_vhost_config_slave.py

- name: Ensure EA4 is enabled for php-fpm
  file:
    path: /etc/cpanel/ea4
    state: directory

- name: Ensure isEA4
  file:
    path: /etc/cpanel/ea4/is_ea4
    state: touch

- lineinfile:
    path: /etc/sysconfig/crond
    regexp: '^CRONDARGS='
    line: 'CRONDARGS="-c"'

- name: Add cluster cron failover job in /etc/crontab
  cron:
    name: XtendWeb crond failover
    cron_file: "/etc/crontab"
    user: root
    job: "/opt/nDeploy/scripts/cluster_cron_server_status_check.py"
  when:
    - inventory_hostname == groups['ndeploydbslave'][0]
