#!/bin/bash

/usr/sbin/nginx -t 2> /dev/null
if [ $? -ne 0 ];then
  ##Attempt to re-generate all nginx config
  touch /opt/nDeploy/conf/skip_nginx_reload
  touch /opt/nDeploy/conf/skip_php-fpm_reload

  echo -e '\e[93m Attempting to regenerate all nginx conf  \e[0m'
  for CPANELUSER in $(cat /etc/domainusers|cut -d: -f1);do nice --adjustment=15 /opt/nDeploy/scripts/generate_config.py $CPANELUSER;done

  rm -f /opt/nDeploy/conf/skip_nginx_reload /opt/nDeploy/conf/skip_php-fpm_reload

  # Reloading nginx
  /usr/sbin/nginx -s reload
fi
# Workaround for unison memory issue
if [ -f /opt/nDeploy/conf/ndeploy_cluster.yaml ];then
  /usr/sbin/service ndeploy_unison stop
  sleep 5
  /usr/sbin/service ndeploy_unison start
fi
