---

- name: check if maxscale proxy is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
  register: maxscale

- name: Install MaxScale rpm
  yum:
    name: https://dlm.mariadb.com/1513946/MaxScale/2.4.16/centos/7/x86_64/maxscale-2.4.16-1.rhel.7.x86_64.rpm
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_distribution_major_version|int == 7

- name: Install MaxScale rpm
  yum:
    name: https://dlm.mariadb.com/1513928/MaxScale/2.4.16/centos/8/x86_64/maxscale-2.4.16-1.rhel.8.x86_64.rpm
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_distribution_major_version|int == 8

- name: Generate maxkeys
  shell: maxkeys
  when:
    - maxscale.stat.exists == false

- name: Generate maxscale password
  shell: maxpasswd /var/lib/maxscale/ {{ MYSQLPASS }} > /root/xtendweb_maxscale

- file:
    path: /var/lib/maxscale/.secrets
    owner: maxscale
    group: maxscale
    mode: 0400
