---

- name: check if maxscale proxy is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
  register: maxscale

- name: Install MaxScale rpm
  yum:
    name: {{ MAXSCALE7URL }}
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_distribution_major_version|int == 7

- name: Install MaxScale rpm
  yum:
    name: {{ MAXSCALE8URL }}
    state: present
    validate_certs: no
    disable_gpg_check: yes
  when:
    - ansible_distribution_major_version|int == 8

- name: Delete previous maxscale secrets
  file:
    state: absent
    path: /var/lib/maxscale/.secrets
  when:
    - maxscale.stat.exists == false

- name: Generate maxkeys
  shell: maxkeys
  when:
    - maxscale.stat.exists == false

- name: Generate maxscale password
  shell: maxpasswd /var/lib/maxscale/ {{ MYSQLPASS }} > /root/xtendweb_maxscale

- file:
    path: /var/lib/maxscale/.secrets
    owner: maxscale
    group: maxscale
    mode: 0400
