---

- name: Ensure EPEL and XtendWeb repo is present
  yum: name={{ item }} state=present
  with_items:
    - nDeploy-release-centos
    - epel-release

- name: Install XtendWeb rpm's on master
  yum: name={{ item }} enablerepo=ndeploy,epel state=present
  with_items:
   - csync2-nDeploy
   - unison-nDeploy
   - python-pip

- name: Install MySQL-python
  pip:
    name: MySQL-python
    state: present

- name: Setup nginx config directories on master
  file: path=/etc/nginx/{{ item }} state=directory
  with_items:
    - "{{ groups['ndeployslaves'] }}"
