---

- name: Ensure EPEL and XtendWeb repo is present
  yum: name={{ item }} state=present
  with_items:
    - nDeploy-release-centos
    - epel-release

- name: Install XtendWeb rpm's on master
  yum: name={{ item }} enablerepo=ndeploy-edge,epel state=present
  with_items:
   - csync2-nDeploy
   - unison-nDeploy
   - python-pip
   - redhat-lsb-core
   - stunnel
   - redis
   - haproxy
   - geodns-nDeploy

- name: Setup nginx config directories on master
  file: path=/etc/nginx/{{ item }} state=directory
  with_items:
    - "{{ groups['ndeployslaves'] }}"

- name: Fix /root/.my.cnf quotes
  shell: /opt/nDeploy/scripts/fix_mysql_cnf_quotes.py

- lineinfile:
    path: /etc/sysconfig/crond
    regexp: '^CRONDARGS='
    line: 'CRONDARGS="-c"'

- name: Set cluster cron master
  shell: "echo $HOSTNAME > /var/spool/cron/.cron.hostname"

- name: Add cluster cron failover job in /etc/crontab
  cron:
    name: XtendWeb crond failover
    cron_file: "/etc/crontab"
    user: root
    job: "/usr/bin/touch /var/spool/cron/.cron.hostname"

- name: Create ndeploy master yaml
  template:
    src: ndeploy_master.yaml.j2
    dest: /opt/nDeploy/conf/ndeploy_master.yaml

- name: Allow server status check from all cluster nodes
  template:
    src: nginx_status_allow.conf.j2
    dest: /etc/nginx/conf.d/nginx_status_allow.conf
