---

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/root/xtendweb_*"

- name: Restart crond on master
  service: name=crond enabled=yes state=restarted

- name: Restart gdnsd on master
  service: name=gdnsd enabled=yes state=restarted
  when: dns == "geodns"

- name: Restart cpanel on master
  service: name=cpanel enabled=yes state=restarted

- name: Setup monit for gdnsd
  template:
    src: gdnsd.conf.j2
    dest: /etc/monit.d/gdnsd.conf
  when: dns == "geodns"

- name: Restart monit
  service: name=monit enabled=yes state=restarted
  when: dns == "geodns"
