---

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_fileglob:
    - "/root/xtendweb_*"

- name: Add MaxScale autorecovery in /etc/crontab
  cron:
    name: XtendWeb MaxScale autorecovery
    cron_file: "/etc/crontab"
    user: root
    job: "/opt/nDeploy/scripts/maxscale_master_autorecover.sh"
    minute: "*/5"

- name: Add MaxScale status update in /etc/crontab
  cron:
    name: XtendWeb MaxScale status update
    cron_file: "/etc/crontab"
    user: root
    job: "/opt/nDeploy/scripts/check_maxscale_status.sh"
    minute: "*/5"

- name: Restart crond on master
  service: name=crond enabled=yes state=restarted

- name: Restart gdnsd on master
  service: name=gdnsd enabled=yes state=restarted
  when: dns == "geodns"

- name: Restart cpanel on master
  service: name=cpanel enabled=yes state=restarted

- name: Setup monit for gdnsd
  template:
    src: gdnsd.conf.j2
    dest: /etc/monit.d/gdnsd.conf
  when: dns == "geodns"

- name: Restart monit
  service: name=monit enabled=yes state=restarted
  when: dns == "geodns"
