---

- name: Clean up temporary files
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - xtendweb_{{ mainip }}
    - xtendweb_{{ mainip }}-dnsrole
    - /root/xtendweb_mysql_replication.sql
    -  /root/xtendweb_mysql_all.sql
    - /root/xtendweb_accesshash_temp
    - xtendweb_csf

- name: Add MaxScale status update in /etc/cron.d/xtendweb-cron
  cron:
    name: XtendWeb MaxScale status update
    cron_file: "/etc/cron.d/xtendweb-cron"
    user: root
    job: "/opt/nDeploy/scripts/check_maxscale_status.sh"
    minute: "*/5"

- name: Restart crond on slave
  service: name=crond enabled=yes state=restarted

- name: Restart cpanel on slave
  service: name=cpanel enabled=yes state=restarted

- name: Start httpd on slave
  service: name=httpd enabled=yes state=started

- name: Disable universal-hooks yum plugin on slaves
  lineinfile:
    path: /etc/yum/pluginconf.d/universal-hooks.conf
    regexp: '^enabled='
    line: 'enabled=0'
  ignore_errors: yes

- name: Setup monit for gdnsd
  template:
    src: gdnsd.conf.j2
    dest: /etc/monit.d/gdnsd.conf
  when: dns == "geodns"

- name: Restart monit
  service: name=monit enabled=yes state=restarted
  when: dns == "geodns"
