---

- name: Setup stunnel config on master
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

#- name: Start HAPROXY on master
#  service: name=haproxy enabled=yes state=started
