---

- name: Stop Exim service
  service: name=exim state=stopped
  ignore_errors: yes

- name: remove exim from slave
  yum: name=exim state=absent

- name: Ensure  redhat-lsb-core is present
  yum: name={{ item }} state=present
  with_items:
    - redhat-lsb-core

- name: install PostFix server
  yum: name=postfix state=present

- name: Setup Postfix configuration
  shell: "{{ item }}"
  with_items:
    - postconf -e "smtpd_recipient_restrictions = permit_mynetworks, reject_unauth_destination"
    - postconf -e "relay_recipient_maps ="
    - postconf -e "relay_domains = hash:/etc/postfix/relaydomains"
    - postconf -e "relay_domains = hash:/etc/postfix/transportmaps"
    - postconf -e "inet_interfaces = all"
    - postconf -e "inet_protocols = ipv4"
    - postconf -e "smtp_tls_security_level = may"
    - postconf -e "smtpd_tls_security_level = may"
    - postconf -e "smtpd_tls_key_file = /var/cpanel/ssl/exim/exim.key"
    - postconf -e "smtpd_tls_cert_file = /var/cpanel/ssl/exim/exim.crt"
    - postconf -e "smtpd_tls_loglevel = 1"
    - postconf -e "smtpd_tls_session_cache_timeout = 3600s"
    - postconf -e "tls_random_source = dev:/dev/urandom"

- name: Setup backupMX update script
  template:
    src: postfix_backupmx_update.sh.j2
    dest: /opt/nDeploy/scripts/postfix_backupmx_update.sh
    mode: 0755


- name: Restart Postfix server
  service: name=postfix enabled=yes state=restarted
