---

- name: disable Exim
  shell: "/usr/local/cpanel/bin/whmapi1 configureservice service=exim enabled=0 monitored=0"
  ignore_errors: yes

- name: Stop Exim service
  service: name=exim state=stopped
  ignore_errors: yes

- name: remove exim from slave
  yum: name=exim state=absent disable_excludes=all

- name: Ensure  redhat-lsb-core is present
  yum: name={{ packages }} state=present
  vars:
    packages:
      - redhat-lsb-core

- name: install PostFix server
  yum: name=postfix state=present

- name: install postgrey greylisting service
  yum: name=postgrey state=present

- name: Setup Postfix configuration
  shell: "{{ item }}"
  with_items:
    - postconf -e "smtpd_delay_reject = yes"
    - postconf -e "smtpd_helo_required = yes"
    - postconf -e "smtpd_helo_restrictions = permit_mynetworks, reject_non_fqdn_hostname, reject_invalid_hostname, permit"
    - postconf -e "smtpd_relay_restrictions = permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination"
    - postconf -e "smtpd_recipient_restrictions = reject_unauth_pipelining, reject_non_fqdn_recipient, reject_unknown_recipient_domain, permit_mynetworks, permit_sasl_authenticated, reject_unauth_destination, reject_rbl_client relays.ordb.org, reject_rbl_client list.dsbl.org, reject_rbl_client sbl-xbl.spamhaus.org, check_policy_service unix:postgrey/socket, permit"
    - postconf -e "relay_recipient_maps ="
    - postconf -e "relay_domains = hash:/etc/postfix/transportmaps"
    - postconf -e "recipient_bcc_maps = hash:/etc/postfix/recipient_bcc"
    - postconf -e "inet_interfaces = all"
    - postconf -e "inet_protocols = ipv4"
    - postconf -e "smtp_tls_security_level = may"
    - postconf -e "smtpd_tls_security_level = may"
    - postconf -e "smtpd_tls_key_file = /var/cpanel/ssl/exim/exim.key"
    - postconf -e "smtpd_tls_cert_file = /var/cpanel/ssl/exim/exim.crt"
    - postconf -e "smtpd_tls_loglevel = 1"
    - postconf -e "smtpd_tls_session_cache_timeout = 3600s"
    - postconf -e "tls_random_source = dev:/dev/urandom"
    - postconf -e "smtpd_sasl_type = dovecot"
    - postconf -e "smtpd_sasl_path = /var/run/dovecot/auth-client"
    - postconf -e "smtpd_sasl_auth_enable = yes"

- name: Setup backupMX update script
  template:
    src: postfix_backupmx_update.sh.j2
    dest: /opt/nDeploy/scripts/postfix_backupmx_update.sh
    mode: 0755

- name: Ensure submission port is enabled in postfix
  lineinfile:
    path: /etc/postfix/master.cf
    regexp: '^#submission'
    line: 'submission inet n       -       n       -       -       smtpd'

- name: remove ssmtp from slave
  yum: name=ssmtp state=absent

- name: Restart postgrey greylisting service
  service: name=postgrey enabled=yes state=restarted

- name: Restart Postfix server
  service: name=postfix enabled=yes state=restarted
