---

- name: check if maxscale proxy is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MAXSCALE_SETUP_LOCK_DO_NOT_REMOVE
  register: maxscale

- name: Install MaxScale rpm
  yum:
    name: https://downloads.mariadb.com/MaxScale/2.1.3/rhel/7/x86_64/maxscale-2.1.3-1.rhel.7.x86_64.rpm
    state: present
  when:
    - ansible_lsb.major_release|int >= 7

- name: Install MaxScale rpm
  yum:
    name: https://downloads.mariadb.com/MaxScale/2.1.3/rhel/6/x86_64/maxscale-2.1.3-1.rhel.6.x86_64.rpm
    state: present
  when:
    - ansible_lsb.major_release|int < 7

- name: Generate maxkeys
  shell: maxkeys
  when:
    - maxscale.stat.exists == false

- name: Generate maxscale password
  shell: maxpasswd /var/lib/maxscale/ {{ MYSQLPASS }} > /root/xtendweb_maxscale

- file:
    path: /var/lib/maxscale/.secrets
    owner: maxscale
    group: maxscale
    mode: 0400
