---

- name: Setup httpd systemd service file
  template:
    src: httpd.service.j2
    dest: /etc/systemd/system/httpd.service

- name: just force systemd to reread configs
  systemd:
    daemon_reload: yes

- name: Setup monit for httpd
  template:
    src: apache.conf.j2
    dest: /etc/monit.d/apache.conf

- name: Restart monit
  service: name=monit enabled=yes state=restarted
