---

- name: check if Mysql replication is setup
  stat:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
  register: mysqlsetup

- name: generate start replication query
  template:
    src: replication.j2
    dest: /root/xtendweb_mysql_replication.sql

- name: Setup mysql replication
  shell: mysql < /root/xtendweb_mysql_replication.sql
  when:
    - mysqlsetup.stat.exists == false

- file:
    path: /opt/nDeploy/conf/XTENDWEB_MYSQL_SETUP_LOCK_DO_NOT_REMOVE
    state: touch
